netutil.o: netutil.cc ../nmap_config.h ../nbase/nbase.h \
 ../nbase/nbase_config.h ../nbase/getopt.h ../nbase/nbase_ipv6.h \
 netutil.h ../libpcap/pcap.h ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
PacketElement.o: PacketElement.cc PacketElement.h ../nbase/nbase.h \
 ../nbase/nbase_config.h ../nbase/getopt.h ../nbase/nbase_ipv6.h \
 netutil.h ../libpcap/pcap.h ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
NetworkLayerElement.o: NetworkLayerElement.cc NetworkLayerElement.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
ARPHeader.o: ARPHeader.cc ARPHeader.h NetworkLayerElement.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
PacketElement.o: PacketElement.cc PacketElement.h ../nbase/nbase.h \
 ../nbase/nbase_config.h ../nbase/getopt.h ../nbase/nbase_ipv6.h \
 netutil.h ../libpcap/pcap.h ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
NetworkLayerElement.o: NetworkLayerElement.cc NetworkLayerElement.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
TransportLayerElement.o: TransportLayerElement.cc TransportLayerElement.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h IPv4Header.h \
 NetworkLayerElement.h IPv6Header.h
ARPHeader.o: ARPHeader.cc ARPHeader.h NetworkLayerElement.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
EthernetHeader.o: EthernetHeader.cc EthernetHeader.h \
 DataLinkLayerElement.h PacketElement.h ../nbase/nbase.h \
 ../nbase/nbase_config.h ../nbase/getopt.h ../nbase/nbase_ipv6.h \
 netutil.h ../libpcap/pcap.h ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
ICMPv4Header.o: ICMPv4Header.cc ICMPv4Header.h ICMPHeader.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
ICMPv6Header.o: ICMPv6Header.cc ICMPv6Header.h ICMPHeader.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h IPv6Header.h \
 NetworkLayerElement.h
IPv4Header.o: IPv4Header.cc IPv4Header.h NetworkLayerElement.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
IPv6Header.o: IPv6Header.cc IPv6Header.h NetworkLayerElement.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
TCPHeader.o: TCPHeader.cc TCPHeader.h TransportLayerElement.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
UDPHeader.o: UDPHeader.cc UDPHeader.h TransportLayerElement.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
RawData.o: RawData.cc RawData.h ApplicationLayerElement.h PacketElement.h \
 ../nbase/nbase.h ../nbase/nbase_config.h ../nbase/getopt.h \
 ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h ../libpcap/pcap/pcap.h \
 ../libpcap/pcap/bpf.h ../libdnet-stripped/include/dnet.h \
 ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
HopByHopHeader.o: HopByHopHeader.cc HopByHopHeader.h \
 IPv6ExtensionHeader.h PacketElement.h ../nbase/nbase.h \
 ../nbase/nbase_config.h ../nbase/getopt.h ../nbase/nbase_ipv6.h \
 netutil.h ../libpcap/pcap.h ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
DestOptsHeader.o: DestOptsHeader.cc DestOptsHeader.h HopByHopHeader.h \
 IPv6ExtensionHeader.h PacketElement.h ../nbase/nbase.h \
 ../nbase/nbase_config.h ../nbase/getopt.h ../nbase/nbase_ipv6.h \
 netutil.h ../libpcap/pcap.h ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
FragmentHeader.o: FragmentHeader.cc FragmentHeader.h \
 IPv6ExtensionHeader.h PacketElement.h ../nbase/nbase.h \
 ../nbase/nbase_config.h ../nbase/getopt.h ../nbase/nbase_ipv6.h \
 netutil.h ../libpcap/pcap.h ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
RoutingHeader.o: RoutingHeader.cc RoutingHeader.h IPv6ExtensionHeader.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h
PacketParser.o: PacketParser.cc PacketParser.h ApplicationLayerElement.h \
 PacketElement.h ../nbase/nbase.h ../nbase/nbase_config.h \
 ../nbase/getopt.h ../nbase/nbase_ipv6.h netutil.h ../libpcap/pcap.h \
 ../libpcap/pcap/pcap.h ../libpcap/pcap/bpf.h \
 ../libdnet-stripped/include/dnet.h ../libdnet-stripped/include/dnet/os.h \
 ../libdnet-stripped/include/dnet/eth.h \
 ../libdnet-stripped/include/dnet/ip.h \
 ../libdnet-stripped/include/dnet/ip6.h \
 ../libdnet-stripped/include/dnet/addr.h \
 ../libdnet-stripped/include/dnet/arp.h \
 ../libdnet-stripped/include/dnet/icmp.h \
 ../libdnet-stripped/include/dnet/icmpv6.h \
 ../libdnet-stripped/include/dnet/tcp.h \
 ../libdnet-stripped/include/dnet/udp.h \
 ../libdnet-stripped/include/dnet/sctp.h \
 ../libdnet-stripped/include/dnet/intf.h \
 ../libdnet-stripped/include/dnet/route.h \
 ../libdnet-stripped/include/dnet/fw.h \
 ../libdnet-stripped/include/dnet/tun.h \
 ../libdnet-stripped/include/dnet/blob.h \
 ../libdnet-stripped/include/dnet/rand.h ARPHeader.h \
 NetworkLayerElement.h DataLinkLayerElement.h EthernetHeader.h \
 ICMPHeader.h ICMPv4Header.h ICMPv6Header.h ICMPv6Option.h ICMPv6RRBody.h \
 IPv4Header.h IPv6Header.h RawData.h TCPHeader.h TransportLayerElement.h \
 UDPHeader.h HopByHopHeader.h IPv6ExtensionHeader.h DestOptsHeader.h \
 FragmentHeader.h RoutingHeader.h
